language: node_js
node_js:
- 14
before_script:
  - npm install -g expo-cli
script:
  - npm ci
  - npx jest --ci --passWithNoTests
jobs:
  include:
    - stage: deploy
      node_js: 14
      script:
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive